name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use nightly
        run: rustup default nightly

      - uses: Swatinem/rust-cache@v2

      - name: Run Tests
        run: cargo test --all --verbose

  fmt:
    runs-on: ubuntu-latest
      
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use nightly
        run: rustup default nightly

      - name: Install Rustfmt
        run: rustup component add rustfmt

      - uses: Swatinem/rust-cache@v2
      
      - name: Check Formatting
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Clippy and Rustfmt
        run: rustup component add rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Run Clippy
        run: cargo clippy

